source 'https://rubygems.org'

gem 'pg'
gem 'sinatra'
gem 'rspec'
gem 'capybara'
gem 'pry'
gem 'shoulda-matchers'
gem 'sinatra-contrib', :require => 'sinatra/reloader'
gem 'sinatra-activerecord'
gem 'rake'
